try to make classpath work
it's failing with `java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;`
(among others) which makes me think the new scala plugin was compiled with
scala 2.12 -- unsure how to fix